#!/bin/sh

src_dir="$HOME/Repos/lada/model_weights"
dst_dir="$HOME/Repos/mosaic/mosaic/lada/net/state_dicts"

src="$src_dir/lada_mosaic_detection_model_v2.pt"
dst="$dst_dir/lada_mosaic_detection_model_v2.pt"
ln -sf $src $dst
ls -l $dst

src="$src_dir/lada_mosaic_restoration_model_generic_v1.pth"
dst="$dst_dir/lada_mosaic_restoration_model_generic_v1.pth"
ln -sf $src $dst
ls -l $dst
